# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  idoc-benchmarks:
    dependencies:
    - base
    - idoc
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Language
description: idoc is the ILS-flavoured version of AsciiDoc.
executables:
  idoc:
    dependencies:
    - base
    - idoc
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: Fizzixnerd/idoc
library:
  dependencies:
  - base-noprelude
  - classy-prelude
  - vector
  - megaparsec
  - containers
  - text
  - shakespeare
  - blaze-html
  - pretty
  - GenericPretty
  source-dirs: library
license: MIT
maintainer: Matt Walker
name: idoc
synopsis: AsciiDoc for the Prerex Engine.
tests:
  idoc-test-suite:
    dependencies:
    - base-noprelude
    - classy-prelude
    - idoc
    - tasty
    - tasty-hspec
    - QuickCheck
    - tasty-quickcheck
    - megaparsec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
